version: "3.8"

services:
  dm-hud:
    build: .
    container_name: dm-hud
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
